name: "Secret Scanning"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@v3.95.5
      with:
        extra_args: --only-verified
